services:
  - type: web
    name: final-report-app
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
