"""
Patch script to fix build_sheet8_city in app.py.
Removes corrupted code and 3 duplicate definitions,
replaces with one clean function.
"""

APP_PATH = r"c:\Users\HP\Desktop\project\backend\app.py"

with open(APP_PATH, "r", encoding="utf-8") as f:
    lines = f.readlines()

print(f"Original file: {len(lines)} lines")

# Section 1: Keep lines 1-1129 (index 0-1128)
part1 = lines[0:1129]

# Section 2: New clean code (as a list of lines)
new_lines = []

def add(text):
    new_lines.append(text + "\n")

add('                for _, row in df.head(n_cities).iterrows()]')
add('    except Exception as e:')
add('        print(f"[WARN] _load_city_reference failed: {e}")')
add('        return []')
add('')
add('')
add('# -- Sheet 8 - City -----------------------------------------------------------')
add('')
add('def build_sheet8_city(df1, df2,')
add('                      total_imp, total_clk, ctr_reach,')
add('                      city_db_sheet="Master Database",')
add('                      is_banner=False):')
add('    """Sheet 8: Distribution by City + Creative."""')
add('    info = {')
add('        "matched_line_items": 0,')
add('        "cities_found": 0,')
add('        "city_source": "",')
add('        "warnings": [],')
add('        "debug": {}')
add('    }')
add('')
add('    grand_total = {')
add('        "City": "Grand Total", "Creative": "",')
add('        "Impressions": total_imp, "Clicks": total_clk,')
add('        "Click Rate (CTR)": ctr_reach')
add('    }')
add('')
add('    # -- Phase 1: Line Item Matching --')
add('    li_col1 = detect_line_item_col(df1)')
add('    li_col2 = detect_line_item_col(df2)')
add('    info["debug"]["li_col1"] = li_col1')
add('    info["debug"]["li_col2"] = li_col2')
add('')
add('    matched_df2 = pd.DataFrame()')
add('    if li_col1 and li_col2:')
add('        items1 = [str(v).strip() for v in df1[li_col1].dropna().unique() if str(v).strip()]')
add('')
add('        def get_tokens(s):')
add('            s = str(s).lower()')
add('            if "|" in s:')
add('                s = s.split("|")[-1]')
add("            return set(re.findall(r'[a-z0-9]+', s))")
add('')
add('        def matches_any_line_item(v2_raw):')
add('            v2_tokens = get_tokens(str(v2_raw))')
add('            if not v2_tokens:')
add('                return False')
add('            for i1 in items1:')
add('                i1_tokens = get_tokens(i1)')
add('                if not i1_tokens:')
add('                    continue')
add('                if i1_tokens.issubset(v2_tokens) or v2_tokens.issubset(i1_tokens):')
add('                    return True')
add('            return False')
add('')
add('        mask = df2[li_col2].apply(matches_any_line_item)')
add('        matched_df2 = df2[mask].copy()')
add('        info["matched_line_items"] = int(mask.sum())')
add('        if matched_df2.empty:')
add('            info["warnings"].append("Line item matching found 0 rows. Falling back to all File 2 rows.")')
add('')
add('    if matched_df2.empty:')
add('        matched_df2 = df2.copy()')
add('        info["debug"]["fallback_used"] = True')
add('')
add('    # -- Phase 2: Detect City column --')
add('    db_cities_raw = load_city_db_sheet(city_db_sheet)')
add('    if not db_cities_raw:')
add('        db_cities_raw = load_city_db_sheet("Master Database")')
add('        if db_cities_raw:')
add('            info["warnings"].append(f"Sheet \'{city_db_sheet}\' not found. Using Master Database.")')
add('    db_lookup = {c["name"].strip().lower(): c for c in db_cities_raw}')
add('    db_city_names = {c["name"] for c in db_cities_raw if c.get("name")}')
add('')
add('    city_col = _find_city_column(matched_df2, db_city_names)')
add('    if city_col is None:')
add('        for col in matched_df2.columns:')
add('            if str(col).strip().lower() == "city":')
add('                city_col = col')
add('                break')
add('    if city_col is None:')
add('        for col in matched_df2.columns:')
add('            if "city" in str(col).strip().lower():')
add('                city_col = col')
add('                break')
add('    if city_col is None:')
add('        info["warnings"].append("No \'City\' column detected in File 2.")')
add('        return [], grand_total, info')
add('')
add('    # -- Phase 3: Detect weight and line-item columns --')
add('    weight_col2 = next(')
add('        (c for c in matched_df2.columns if "impression" in str(c).lower() or "weight" in str(c).lower()),')
add('        None,')
add('    )')
add('    if weight_col2 is None:')
add('        numeric_candidates = [c for c in matched_df2.columns if pd.api.types.is_numeric_dtype(matched_df2[c])]')
add('        weight_col2 = numeric_candidates[0] if numeric_candidates else matched_df2.columns[-1]')
add('')
add('    li_col2_matched = next(')
add('        (c for c in matched_df2.columns if "line item" in str(c).lower()),')
add('        matched_df2.columns[0]')
add('    )')
add('')
add('    # -- Phase 4: Filter by line item & group by city --')
add('    li_col1_real = next(')
add('        (c for c in df1.columns if "line item" in str(c).lower()),')
add('        df1.columns[0]')
add('    )')
add('    target_li_names = {')
add('        str(v).strip()')
add('        for v in df1[li_col1_real].dropna().astype(str).unique()')
add('        if str(v).strip()')
add('    }')
add('')
add('    def normalize_li(val):')
add('        val_str = str(val).strip()')
add('        if "|" in val_str:')
add('            val_str = val_str.split("|", 1)[1].strip()')
add('        return val_str')
add('')
add('    mask2 = matched_df2[li_col2_matched].apply(lambda v: normalize_li(v) in target_li_names)')
add('    filtered_df2 = matched_df2[mask2].copy()')
add('    info["debug"]["target_line_items"] = sorted(target_li_names)')
add('    info["debug"]["filtered_rows"] = len(filtered_df2)')
add('')
add('    if filtered_df2.empty:')
add('        info["warnings"].append("No exact Line Item matches found after normalization. Using all data as fallback.")')
add('        filtered_df2 = matched_df2.copy()')
add('')
add('    city_groups = filtered_df2.groupby(city_col, dropna=False).agg({')
add('        weight_col2: "sum",')
add('        li_col2_matched: lambda x: sorted({')
add('            normalize_li(v) for v in x.dropna().astype(str) if normalize_li(v)')
add('        }),')
add('    }).reset_index()')
add('')
add('    input_cities_map = {}')
add('    for _, row in city_groups.iterrows():')
add('        name = str(row[city_col]).strip()')
add('        if name and name.lower() not in {"nan", "none", ""}:')
add('            input_cities_map[name.lower()] = {')
add('                "name": name,')
add('                "weight": safe_float(row[weight_col2]),')
add('                "creatives": row[li_col2_matched],')
add('            }')
add('')
add('    # -- Phase 5: Enrich with DB creatives --')
add('    final_cities = []')
add('    for city_key, inp in input_cities_map.items():')
add('        db_city = db_lookup.get(city_key)')
add('        final_cities.append({')
add('            "name": inp["name"],')
add('            "weight": inp["weight"],')
add('            "creatives": db_city["creatives"] if db_city and db_city.get("creatives") else inp["creatives"],')
add('        })')
add('')
add('    # -- Phase 6: Banner capping / supplementation --')
add('    if is_banner:')
add('        if len(final_cities) > 60:')
add('            final_cities.sort(key=lambda x: x["weight"], reverse=True)')
add('            final_cities = final_cities[:60]')
add('        if len(final_cities) < 40:')
add('            existing_names = {c["name"].lower() for c in final_cities}')
add('            master_cities = load_city_db_sheet("Master Database")')
add('            added = 0')
add('            for mc in master_cities:')
add('                if added >= (40 - len(final_cities)):')
add('                    break')
add('                if mc["name"].lower() not in existing_names:')
add('                    final_cities.append({')
add('                        "name": mc["name"],')
add('                        "weight": mc["weight"],')
add('                        "creatives": mc.get("creatives") or ["General Creative"],')
add('                    })')
add('                    added += 1')
add('')
add('    final_cities.sort(key=lambda x: x["weight"], reverse=True)')
add('')
add('    # -- Phase 7: Build city x creative rows --')
add('    creative_col1 = next(')
add('        (c for c in df1.columns if "creative" in str(c).lower() and "id" not in str(c).lower()),')
add('        df1.columns[0]')
add('    )')
add('    all_f1_creatives = sorted(list(set(df1[creative_col1].dropna().astype(str))))')
add('    if not all_f1_creatives:')
add('        all_f1_creatives = ["Default Creative"]')
add('')
add('    rows = []')
add('    for city_info_item in final_cities:')
add('        city_name = city_info_item["name"]')
add('        city_weight = max(city_info_item["weight"], 1.0)')
add('        city_creatives = city_info_item.get("creatives") or all_f1_creatives')
add('        weight_per_cr = city_weight / len(city_creatives)')
add('        for cr in city_creatives:')
add('            rows.append({"City": city_name, "Creative": cr, "_weight": weight_per_cr})')
add('')
add('    if not rows:')
add('        for city_name in ["Sydney", "Melbourne", "Brisbane", "Perth"]:')
add('            rows.append({"City": city_name, "Creative": all_f1_creatives[0], "_weight": 1.0})')
add('')
add('    # -- Phase 8: Distribute impressions & clicks --')
add('    df_rows = pd.DataFrame(rows)')
add('    total_weight = df_rows["_weight"].sum()')
add('    scaled_imps = _largest_remainder(df_rows["_weight"].tolist(), total_weight, total_imp)')
add('    scaled_imps = deduplicate_preserving_sum(scaled_imps, gap=1)')
add('')
add('    CTR_LO, CTR_HI = 0.0035, 0.0056')
add('    raw_clks = [')
add('        max(1, int(imp * random.uniform(CTR_LO, CTR_HI))) if imp >= 180 else 0')
add('        for imp in scaled_imps')
add('    ]')
add('    raw_sum = sum(raw_clks) or 1')
add('    scaled_clks = [')
add('        max(1, int(round(r * total_clk / raw_sum))) if scaled_imps[i] >= 180 else 0')
add('        for i, r in enumerate(raw_clks)')
add('    ]')
add('    drift = total_clk - sum(scaled_clks)')
add('    if drift > 0:')
add('        eligible = [i for i, imp in enumerate(scaled_imps) if imp >= 180] or list(range(len(scaled_imps)))')
add('        scaled_clks[max(eligible, key=lambda i: scaled_imps[i])] += drift')
add('    elif drift < 0:')
add('        for _ in range(abs(drift)):')
add('            eligible = [i for i, c in enumerate(scaled_clks) if c > 1]')
add('            if not eligible:')
add('                break')
add('            scaled_clks[max(eligible, key=lambda i: scaled_clks[i])] -= 1')
add('')
add('    df_rows["Impressions"] = scaled_imps')
add('    df_rows["Clicks"] = scaled_clks')
add('    final_df = df_rows.drop(columns=["_weight"])')
add('    total_clk_sum = int(df_rows["Clicks"].sum())')
add('')
add('    total_row = {')
add('        "City": "Grand Total", "Creative": "",')
add('        "Impressions": total_imp, "Clicks": total_clk_sum,')
add('        "Click Rate (CTR)": pct(total_clk_sum, total_imp),')
add('    }')
add('')
add('    info["cities_found"] = len(final_df["City"].drop_duplicates())')
add('    info["city_source"] = "input"')
add('    return final_df.to_dict(orient="records"), total_row, info')
add('')

# Section 3: Keep lines 1392-2584 (index 1391-2583)
part3 = lines[1391:2584]

# Section 4: Skip lines 2585-2720 (3rd duplicate definition, index 2584-2719)
# Section 5: Keep lines 2721 onwards (index 2720 to end)
part5 = lines[2720:]

# Combine
result = part1 + new_lines + part3 + part5

# Fix the call site
fixed_result = []
for line in result:
    if "build_sheet8_city(df1, df2, total_imp, city_sheet, is_banner=is_banner)" in line:
        line = line.replace(
            "build_sheet8_city(df1, df2, total_imp, city_sheet, is_banner=is_banner)",
            "build_sheet8_city(df1, df2, total_imp, total_clk, ctr_reach, city_sheet, is_banner=is_banner)"
        )
    fixed_result.append(line)

with open(APP_PATH, "w", encoding="utf-8") as f:
    f.writelines(fixed_result)

print(f"Patched file: {len(fixed_result)} lines")
print("Done! build_sheet8_city consolidated and call site updated.")
